version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes: 
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kiosk
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul

volumes: 
  database: